### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by frenzymadness** [sphinx-contrib/zopeext#11]
Hello.

Do you plan a new release, please? I'd like to update zope-interface to version 6 in Fedora Linux but version 0.3.3 of this project requires zope-interface < 6 so I can either hack around it or wait for a new release because the current main branch contains `zope.interface>=5.5.2` so no upper limit anymore.

**Comment by frenzymadness** [comment]
Yes, it sounds reasonable. By the way, why do you need PDM for testing with a matrix of versions? I mean, tox can do that and it's a defacto standard in the Python ecosystem.

**Comment by mforbes** [comment]
I use `nox` for testing a matrix of versions, but was using some tools based on Poetry to determine automatically determine which versions to test. Poetry's aggressive insistence on upper bounds lead to these issues, so I have switched to PRM and was trying to find a similar way of extracting the allowed versions with PDM, but have not had any luck yet.

For this project, I just manually specified the matrix in `noxfile.py`, but this violates DRY: the information should be extracted from `pyproject.toml`.  If you have suggestions, I would love to hear.  The whole python packaging ecosystem is really frustrating right now.

4.0.0 should be released.

**Comment by mforbes** [comment]
Okay: Release 0.4.2 should work.  I had some release issues with the others.

**Comment by frenzymadness** [comment]
> Are there tools that help `tox` extract the allowed dependencies automatically?

The biggest issue I see here is that it's hard to tell which versions you want to test if you only have a range of supported versions. Let's say your app works fine with foobar >=3;<6 - does that mean you want to test it with the latest version of  foobar in the major branches (3,4,5) or all of them (3.*, 4.*, 5.*) etc.?

I agree that it would be great to have a tool like that.

**Comment by mforbes** [comment]
This is an interesting question: if you test with too many versions, things quickly get out of control.  At a start, I would probably want to test with the outer versions: 3.0.0 and 5.x.  For CI, if both those work, then I would assume the range inside works (unless specified otherwise).  If you have $N$ major packages to test against, then this becomes $N \choose 2 = N(N-1)/2$ tests, which is probably feasible.

When developing, then one should be able to add the latest inner versions 3.x, 4.x, 5.x.  This of course could rapidly get out of control, so probably should be done stochastically just to identify potential conflicts.

Back when I thought Poetry's insistence on upper bounds might be reasonable, I thought such a strategy should be used to determine the upper bound.  Now I am pretty convinced [1][] that upper bounds should not be used unless an actual problem is found.

[1]: <https://iscinumpy.dev/post/bound-version-constraints/>
